#!/bin/sh

set -eu

choice=$(printf '%s\n' 'Lock' 'Suspend' 'Log out' 'Reboot' 'Power off' | \
  wofi --dmenu --prompt 'Session') || exit 0

case "$choice" in
  Lock) hyprlock ;;
  Suspend) systemctl suspend ;;
  'Log out') uwsm stop ;;
  Reboot) systemctl reboot ;;
  'Power off') systemctl poweroff ;;
esac
