# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  theme:
    selectedLineBgColor:
      # - "#314154"
      - "#013e4a"
# # Keybindings
# keybinding:
#   universal:
#     quit: <esc>
git:
  paging:
    colorArg: always
    pager: ""
    useConfig: false

# When git-delta is installed, the pager can be enabled with:
# git:
#   paging:
#     colorArg: always
#     pager: delta --dark --paging=never --syntax-theme base16-256 -s --wrap-max-lines=10
#     useConfig: false
