#!/bin/bash

options=(
    style=round
    width=6.0
    hidpi=off
    active_color=0xff8aadf4
    inactive_color=0x60585b70
    background_color=0x302c2e34
    blur_radius=25
)

borders "${options[@]}"
