# ~/.bashrc: interactive Bash configuration managed by mydotfiles.

case $- in
  *i*) ;;
  *) return ;;
esac

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

NVM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/nvm"
export NVM_DIR
if [[ -s "$NVM_DIR/nvm.sh" ]]; then
  . "$NVM_DIR/nvm.sh"
fi
if [[ -s "$NVM_DIR/bash_completion" ]]; then
  . "$NVM_DIR/bash_completion"
fi
