general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(1a1b26ff)
    blur_passes = 0
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(c0caf5ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(787c99ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 95
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 56
    position = 0, -60
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    outer_color = rgba(7aa2f7ff)
    inner_color = rgba(24283bee)
    font_color = rgba(c0caf5ff)
    fail_color = rgba(f7768eff)
    placeholder_text = <i>Contrasena</i>
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    rounding = 10
    shadow_passes = 2
}
